config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-peach-tortoise.sh
        container: qc.acc_frumpy-pear-barnacle
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-auburn-bandicoot.sh
        container: qc.doc_randy-khaki-labradoodle
      github.com/ropensci/rdatacite__2:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-gold-bloodhound.sh
        container: qc.doc_zippy-ivory-affenpinscher
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-amaranth-alligator.sh
        container: qc.lic_gamy-violet-fox
  QC.Met:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-razzmatazz-woodpecker.sh
        container: qc.met_breezy-wisteria-chamois
timeout: 600
