config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-bronze-chinchilla.sh
        container: qc.acc_flimsy-cream-quoll
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-zucchini-ibis.sh
        container: qc.doc_gimpy-linen-quetzal
      github.com/ropensci/rdatacite__2:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-emerald-discus.sh
        container: qc.doc_pasty-goldenrod-dog
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-ivory-angelfish.sh
        container: qc.lic_greasy-scarlet-numbat
  QC.Met:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-rust-flounder.sh
        container: qc.met_breezy-ivory-reindeer
timeout: 600
