config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-asparagus-urchin.sh
        container: qc.acc_jumpy-firebrick-tang
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-burgundy-olm.sh
        container: qc.doc_blurry-maroon-moose
      github.com/ropensci/rdatacite__2:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-persimmon-cuttlefish.sh
        container: qc.doc_snazzy-cornflower-bullfrog
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-myrtle-mole.sh
        container: qc.lic_homely-lime-iguana
  QC.Met:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-gamboge-ocelot.sh
        container: qc.met_silly-auburn-lionfish
timeout: 600
