config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-smalt-squid.sh
        container: qc.acc_slaphappy-razzmatazz-deer
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-yellow-zonkey.sh
        container: qc.doc_gloppy-green-lemur
      github.com/ropensci/rdatacite__2:
        commands:
        - /usr/bin/env sh .sqa/script.beady-olivine-guppy.sh
        container: qc.doc_gloppy-bistre-zonkey
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.homely-amber-uguisu.sh
        container: qc.lic_stuffy-blue-rhinoceros
  QC.Met:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-sepia-magpie.sh
        container: qc.met_slaphappy-indigo-civet
timeout: 600
