config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-charcoal-duck.sh
        container: qc.acc_hazy-plum-lemur
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite find_readme.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-white-affenpinscher.sh
        container: qc.doc_ugly-beige-anteater
      github.com/ropensci/rdatacite markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-carmine-monster.sh
        container: qc.doc_blurry-yellow-dog
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-tan-molly.sh
        container: qc.lic_zippy-malachite-dog
  QC.Met:
    repos:
      github.com/ropensci/rdatacite validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-magnolia-sloth.sh
        container: qc.met_thirsty-apricot-mandrill
timeout: 600
