config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-gold-frigatebird.sh
        container: qc.acc_pretty-denim-mongrel
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-carmine-wolfhound.sh
        container: qc.doc_crappy-pear-stingray
      github.com/ropensci/rdatacite__2:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-alizarin-peccary.sh
        container: qc.doc_hazy-lilac-greyhound
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-saffron-albatross.sh
        container: qc.lic_wiggy-khaki-deer
  QC.Met:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-crimson-tiger.sh
        container: qc.met_gamy-cornflower-cuscus
timeout: 600
