config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite.git
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-denim-caterpillar.sh
        container: qc.acc_sleazy-heliotrope-chamois
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-ruby-harrier.sh
        container: qc.doc_hasty-lilac-cow
      github.com/ropensci/rdatacite__2:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-flax-camel.sh
        container: qc.doc_homey-razzmatazz-octopus
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-olive-avocet.sh
        container: qc.lic_droopy-brown-kiwi
  QC.Met:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-linen-squid.sh
        container: qc.met_stealthy-violet-javanese
timeout: 600
