config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-chartreuse-coral.sh
        container: qc.acc_tasty-malachite-shrimp
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-blue-slug.sh
        container: qc.doc_flabby-linen-bonobo
      github.com/ropensci/rdatacite__2:
        commands:
        - /usr/bin/env sh .sqa/script.homey-cream-macaw.sh
        container: qc.doc_fuzzy-eggplant-catfish
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-zucchini-dunker.sh
        container: qc.lic_scanty-pumpkin-wrasse
  QC.Met:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-pumpkin-gecko.sh
        container: qc.met_smelly-ivory-giraffe
timeout: 600
