config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-beige-uakari.sh
        container: qc.acc_grumpy-cardinal-mole
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-white-toucan.sh
        container: qc.doc_trippy-ivory-molly
      github.com/ropensci/rdatacite__2:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-seashell-tapir.sh
        container: qc.doc_shaggy-smalt-capuchin
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-bistre-sponge.sh
        container: qc.lic_gummy-crimson-dingo
  QC.Met:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-teal-bongo.sh
        container: qc.met_stinky-brass-ray
timeout: 600
