config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ropensci/rdatacite:
      repo: https://github.com/ropensci/rdatacite.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-apricot-tapir.sh
        container: qc.acc_randy-ivory-monster
  QC.Doc:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-charcoal-heron.sh
        container: qc.doc_trippy-buff-albatross
      github.com/ropensci/rdatacite__2:
        commands:
        - /usr/bin/env sh .sqa/script.homely-wisteria-saola.sh
        container: qc.doc_greasy-saffron-oriole
  QC.Lic:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-dandelion-penguin.sh
        container: qc.lic_stinky-puce-bloodhound
  QC.Met:
    repos:
      github.com/ropensci/rdatacite:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-azure-discus.sh
        container: qc.met_goopy-mustard-whippet
timeout: 600
